apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: firstapp
  namespace: default
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: Host(`firstapp.pangarabbit.com`)
      services:
        - name: firstapp
          namespace: default
          port: 10081
  tls:
    certResolver: default
